services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5555:5432
    env_file: .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nextjs:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data
    env_file: .env.production
    command: server --console-address ":9001" /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/devsync;
      /usr/bin/mc anonymous set public myminio/devsync;
      exit 0;
      "

volumes:
  postgres_data:
  minio_storage:
