services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nextjs:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
