services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  livekit:
    image: livekit/livekit-server
    restart: always
    ports:
      - 7880:7880
      - 7881:7881
      - 7882:7882/udp
    volumes:
      - $PWD/livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml --node-ip=127.0.0.1
  nextjs:
    build:
      context: .
      target: dev
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev:prisma
    depends_on:
      - postgres

volumes:
  postgres_data:
